In [12]:
from numpy import *

w= array(arange(0.0,3.1,.1))
print(w[:]) #All of the elements in the array are being printed
print(w[:-2]) #This is printing all of the elements except the last two in the array
print(w[::5]) #This is printing every 5th element in the array, in this case it is in steps of 0.5 since each step is .1
print(w[2:-2:6]) #In this example, it is starting from the 3rd element, in steps of every 6th element,
#and not including the last 2 elements in the array

print('') #space between outputs

vector1=[1,2,3,4,5]
print(type(vector1)) #This displays the data type of the vector which is a list
print(len(vector1)) #This command shows the length/number of items (elements in this case) in the object which is 5
print(shape(vector1)) #This command displays the amount of rows and columns the list has, 5 columns in this case 
print(size(vector1)) #Size is essentially the product the of rows and columns in the list or array which is 5

print('') #space between outputs

A= array([[1.,2.,3.],[4.,5.,6.]]) #[] is the number of rows, number of elements inside are the number of columns
print(type(A)) #The type of this item is 'numpy.ndarray'
print(len(A)) #This array has a length of 2 since there are 2 items within the object
print(shape(A)) #The shape examines the amount of rows and columns which is (2, 3) since this array is a 2x3 matrix
print(size(A)) #The size is 6 due to a total of 6 elements (2x3) in the matrix.
print(A)

print('') #space between outputs

vector2=array(range(2,10))
print(len(vector2)) #Length is the total amount of elements in this array which is 8
print(min(vector2)) #The lowest/minimum value in the given array, which is 2
print(max(vector2)) #The highest/maximum value that the array reaches to, 9
print(sum(vector2)) #This is the sum of all the values in the array, in this example it is 2+3+4+5+6+7+8+9=44
print(sorted(vector2)) #Creates a new copy of the sorted list, in numerical order
print(sort(vector2)) #This sorts the original list instead, I used a different vector to check this (Can only be used for lists)

print('') #space between outputs

same = 4*(ones(11))
print(same)

print('') #space between outputs

B=array([arange(0,29,4),arange(69,61,-1),arange(1.4,-0.8,-0.3)])
print(B)
B[0,3]=1
B[1,3]=2
B[2,3]=3
print(B)

print('') #space between outputs

msame=ones([2,5])
msame[:]=7
msame=vstack((msame,[0,0,0,0,0])) # or can also use msame=vstack((msame,zeros(5)))
msame=vstack((msame,[range(1,6)]))
msame=vstack((msame,[msame[1]*6]))
print(msame)

print('') #space between outputs

Z1=concatenate((B[0],msame[1]))
Z2=concatenate((B[1],msame[2]))
Z3=concatenate((B[2],msame[3]))
Z4=vstack((Z1,Z2,Z3))
print(Z4)

print('') #space between outputs

Vector_a=array([0,1,2])
Vector_b=array([3,4,5])
dot((Vector_a),(Vector_b)) #dot product in 1 line



[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3. ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8]
[0.  0.5 1.  1.5 2.  2.5 3. ]
[0.2 0.8 1.4 2.  2.6]

<class 'list'>
5
(5,)
5

<class 'numpy.ndarray'>
2
(2, 3)
6
[[1. 2. 3.]
 [4. 5. 6.]]

8
2
9
44
[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]

[[ 0.   4.   8.  12.  16.  20.  24.  28. ]
 [69.  68.  67.  66.  65.  64.  63.  62. ]
 [ 1.4  1.1  0.8  0.5  0.2 -0.1 -0.4 -0.7]]
[[ 0.   4.   8.   1.  16.  20.  24.  28. ]
 [69.  68.  67.   2.  65.  64.  63.  62. ]
 [ 1.4  1.1  0.8  3.   0.2 -0.1 -0.4 -0.7]]

[[ 7.  7.  7.  7.  7.]
 [ 7.  7.  7.  7.  7.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  2.  3.  4.  5.]
 [42. 42. 42. 42. 42.]]

[[ 0.   4.   8.   1.  16.  20.  24.  28.   7.   7.   7.   7.   7. ]
 [69.  68.  67.   2.  65.  64.  63.  62.   0.   0.   0.   0.   0. ]
 [ 1.4  1.1 

14

In [1]:
import time

sec = 10
while sec >= 0 :
    print('T minus %d seconds to liftoff!' %(sec))
    time.sleep(1)
    sec-= 1

T minus 10 seconds to liftoff!
T minus 9 seconds to liftoff!
T minus 8 seconds to liftoff!
T minus 7 seconds to liftoff!
T minus 6 seconds to liftoff!
T minus 5 seconds to liftoff!
T minus 4 seconds to liftoff!
T minus 3 seconds to liftoff!
T minus 2 seconds to liftoff!
T minus 1 seconds to liftoff!
T minus 0 seconds to liftoff!


In [2]:
import time

percentage= 0
while percentage < 100:
    print('\033[1;32;48m Hacking into NASA: %d%% Completion \n' %(percentage))
    time.sleep(2)
    percentage += 20
    if percentage==100 :
        print(' Hacking into NASA: %d%% Completion' %(percentage))
        time.sleep(2)
        print('\033[5;31;48m SIKE \n')

 Hacking into NASA: 0% Completion 

 Hacking into NASA: 20% Completion 

 Hacking into NASA: 40% Completion 

 Hacking into NASA: 60% Completion 

 Hacking into NASA: 80% Completion 

 Hacking into NASA: 100% Completion
 SIKE 

