In [2]:
import numpy as np

mylines = np.loadtxt('Hubbard.dat', float)
print(mylines)

[[-2.5000000e+01  1.6000000e+00  9.5834691e-07 -3.0347269e-06]
 [-2.5000000e+01  1.8000000e+00  4.4045126e-06 -1.2795823e-05]
 [-2.5000000e+01  2.0000000e+00  1.5124786e-05 -4.0490983e-05]
 ...
 [ 6.0000000e+01  2.0000000e+01  1.7934706e+00  1.4316591e+01]
 [ 6.0000000e+01  2.2000000e+01  1.7572913e+00  1.3708830e+01]
 [ 6.0000000e+01  2.4000000e+01  1.7230256e+00  1.3145637e+01]]
