In [2]:
from numpy import *

vector1= [6, 8*3, 2.5, 'labtime',sqrt(2)]
print(vector1)
vector2= array(range(0,43,3))
print(vector2)
vector3= arange(18.0,-18.5,-4.5,dtype=float)      
print(vector3)
list1= list(linspace(5,61,16))
print(list1)
name1='Henry'
name2=' Wahhab' #add an extra space to separate names
N=name1+name2 #concatenation
print(N)
Afirst=linspace(3,51,13)
print(Afirst)
Asecond=array(range(0,7))
Asecond[0:4]=Afirst[0:4]
Asecond[4:7]=Afirst[10:13]
print(Asecond)

[6, 24, 2.5, 'labtime', 1.4142135623730951]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42]
[ 18.   13.5   9.    4.5   0.   -4.5  -9.  -13.5 -18. ]
[5.0, 8.733333333333334, 12.466666666666667, 16.2, 19.933333333333334, 23.666666666666668, 27.4, 31.133333333333333, 34.86666666666667, 38.6, 42.333333333333336, 46.06666666666667, 49.8, 53.53333333333333, 57.266666666666666, 61.0]
Henry Wahhab
[ 3.  7. 11. 15. 19. 23. 27. 31. 35. 39. 43. 47. 51.]
[ 3  7 11 15 43 47 51]
