In [76]:
from numpy import *

print(5 > 8) #5 is less than 8 so this statement is False
a1 = 5 < 10 #a1 is stored as True
print(a1)
a2 = 5 > 10 #a2 is stored as False
print(a2)
y = (6 < 10) + (7 > 8) == (5*3 == 60/4) #Since True is stored as 1 and False as 0, this expression is essentially saying 1+0==True (1)
print(y)
b = array([15,6,9,4,11,7,14])
c = array([8,20,9,2,19,7,10])
print(c >= b) #This operator checks every element in each index of array c and determines if that value is 
#greater than or equal to each corresponding element with the same index in array b
print(b == c) #This operator checks each element in both arrays and determines if the corresponding indices are equal or not
print(b != c) #This operator determines which elements in the corresponding indices are not equal
q = b - c > 0
print(any(q)) #This function works by letting at least 1 value of q fullfill the expression and will return True as an ouput 
print(all(q)) #This function only returns True as an output if all the values of q fulfill the expression
A = array([[2,9,4],[-3,5,2],[6,7,-1]])
print(A <= 2) #This checks every value in the matrix and determines if it is less than or equal to 2
r1 =array([8,12,9,4,23,19,10]) #Made the list into an array to avoid error message TypeError: '<=' not supported between instances of 'list' and 'int'
print(r1 <= 10)
r2 = array([8,12,9,4,23,19,10])
s2 = r2 <= 10
print(s2) #Determines whether the statement is True or False for each element in the array
print(r2[s2]) #This is only printing the indices in array r2 that are less than or equal to 10
print(r2[r2 <= 10]) #Similar to the previous command, prints out a new array
x = where(r2 <= 10)
print(r2[x]) #x is stored as a tuple and cannot be changed while s2 is stored as an array
print(r2[where(r2 <= 10)]) #Prints the array r2 with values only less than or equal to 10
print(where(r2 <= 10, 7.0, -3.0)) #This prints array r2 but stores True as 7.0 and stores False as -3.0
print(4 in r2) #Determines whether or not there is a value of 4 in the array of r2
print(3 + 4 < 16 / 2) #7 is less than 8, True
print(3 == (4 < 16) / 2) #3==True/2 where True=1, therefore 3==1/2 is False

print('') #Space between outputs

print(True or False) #The OR operator needs at least one of the inputs to be True for the output to be True
print(25*((True and False) + (not False) + (False or True))) # The AND operators needs both of the inputs to be True in order for the output
#to be True as well, the answer is 50 since 25*((0 + 1 + 1))

print('') #Space between outputs

bb, cc = -2,5
print(-5 < bb < -1) #-2 is greater than -5 and less than -2 therefore True
print(-5 < bb and bb < -1) #Since both separate conditions are True, the AND command outputs True as well
print(not cc < 7) #cc < 7 is True, so the output is Not True and therefore False
print((not cc) < 7) #cc is being stored as True since it is equal to 5, not cc is equal to False which is 0 and 0 < 7 is True
print(not ((cc >= 8) or (bb < -1))) #Since bb < -1 is True, the OR command gives a True output however it becomes 'not True' and therefore False
print(not (cc >= 8) or (bb < -1)) #Simplfying the statement, it becomes not False OR True which is True


False
True
False
True
[False  True  True False  True  True False]
[False False  True False False  True False]
[ True  True False  True  True False  True]
True
False
[[ True False False]
 [ True False  True]
 [False False  True]]
[ True False  True  True False False  True]
[ True False  True  True False False  True]
[ 8  9  4 10]
[ 8  9  4 10]
[ 8  9  4 10]
[ 8  9  4 10]
[ 7. -3.  7.  7. -3. -3.  7.]
True
True
False

True
50

True
True
False
True
False
True
